# Generated by Django 5.2.8 on 2025-12-01 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("editing_prompt", "Editing Prompt"),
                            ("generating", "Generating Videos"),
                            ("completed", "Completed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/data_files/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("xlsx", "Excel")], max_length=10
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list, help_text="Danh sách các columns trong file"
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_file",
                        to="app.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="Prompt template với {{field}} placeholders"
                    ),
                ),
                (
                    "enhanced_template",
                    models.TextField(
                        blank=True, help_text="Prompt đã được Gemini enhance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_template",
                        to="app.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_index",
                    models.IntegerField(help_text="Index của row trong file (0-based)"),
                ),
                ("row_data", models.JSONField(help_text="Dữ liệu của row này")),
                (
                    "prompt_used",
                    models.TextField(help_text="Prompt đã được fill data cho row này"),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "veo_job_id",
                    models.CharField(
                        blank=True,
                        help_text="Job ID từ Veo API",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="app.project",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index"],
            },
        ),
    ]
